import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage } from "@/components/legal/legal-page";
import { buildMetadata } from "@/lib/seo";
import { CONTACT_EMAIL, OPERATOR_NAME } from "@/lib/config";

export const metadata: Metadata = buildMetadata({
  title: "Terms of service",
  description: "The rules for using DevTunnel, the open-source contribution platform.",
  path: "/terms",
});

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of service"
      intro="By using DevTunnel you agree to these terms. If you don't agree, please don't use the service."
    >
      <h2>The service</h2>
      <p>
        DevTunnel is a free platform, operated by {OPERATOR_NAME}, India, that helps contributors
        discover open-source projects and tasks and helps maintainers organise them. It is provided
        &ldquo;as is&rdquo;; features may change or be withdrawn.
      </p>

      <h2>Your account</h2>
      <ul>
        <li>You sign in with GitHub. You are responsible for activity under your account and for keeping your GitHub account secure.</li>
        <li>You must be old enough to hold a GitHub account and to agree to these terms where you live.</li>
        <li>Give accurate information. One person, one account.</li>
      </ul>

      <h2>Acceptable use</h2>
      <p>Do not:</p>
      <ul>
        <li>break the law, or infringe anyone&rsquo;s rights;</li>
        <li>spam, harass or abuse maintainers, contributors or the platform, including with automated or low-effort pull requests;</li>
        <li>submit malware, or content that is hateful, deceptive or that you have no right to share;</li>
        <li>probe, overload, scrape at high volume, or try to bypass access controls or rate limits;</li>
        <li>misuse AI features to generate abusive or misleading content.</li>
      </ul>
      <p>We may remove content or suspend accounts that break these rules.</p>

      <h2>Content you submit</h2>
      <p>
        You keep ownership of what you submit (such as community submissions and feedback). You give
        DevTunnel a non-exclusive licence to host and display it as part of the service. Code you
        contribute to a project on GitHub is governed by that project&rsquo;s licence, not by us.
      </p>

      <h2>Third-party data and AI</h2>
      <p>
        Project, issue and repository information comes from GitHub and from maintainers, and
        summaries or explanations may be generated by AI. They can be incomplete or wrong. Check the
        source before relying on them. DevTunnel is not affiliated with or endorsed by GitHub.
      </p>

      <h2>Sponsorship</h2>
      <p>
        Sponsoring is optional, handled on an external payment page, and does not buy features,
        support or influence. See the <Link href="/refunds">Refund policy</Link>.
      </p>

      <h2>Open source</h2>
      <p>The DevTunnel source code is covered by the licence in its repository, which applies to the code, not to your data or to these terms.</p>

      <h2>Disclaimer and liability</h2>
      <p>
        To the fullest extent the law allows, the service is provided without warranties, and we are
        not liable for indirect or consequential loss, or for any loss beyond what you paid us (which,
        for a free service, is nothing). Nothing here limits liability that cannot be limited by law.
      </p>

      <h2>Ending things</h2>
      <p>You can stop using DevTunnel and delete your account at any time in Settings. We may suspend or end the service or an account for breach of these terms or to protect the platform.</p>

      <h2>Governing law</h2>
      <p>These terms are governed by the laws of India, and the courts of India have jurisdiction, without affecting any mandatory consumer rights you have where you live.</p>

      <h2>Contact and changes</h2>
      <p>Questions: <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>. We may update these terms; continuing to use DevTunnel after a change means you accept it. Our <Link href="/privacy">Privacy policy</Link> explains how we handle personal data.</p>
    </LegalPage>
  );
}
