import type { SupabaseClient } from "@supabase/supabase-js";

/**
 * Sponsors — `devtunnel.sponsorships` (sql/048_sponsorships.sql).
 *
 * Write side used by the Razorpay webhook (src/routes/razorpayWebhook.ts).
 * The public read side (the wall, the monthly total) comes in a later part.
 *
 * Rules every function here follows:
 *  - Idempotent on `razorpay_payment_id` (UNIQUE): a replayed delivery
 *    converges on one row and never creates a second.
 *  - A replay never touches an existing row's `approved`, `hidden`,
 *    `display_name`, `github_username`, `is_anonymous` or `show_amount`.
 *    Those are your moderation edits; only the payment's own state moves.
 *  - Status only moves forward (pending < failed < captured < refunded), so a
 *    late or out-of-order delivery can't undo a newer state.
 *  - New rows start `approved = false` (the column default; never set here).
 *    `tier` / `tier_rank` are GENERATED by the database and never written.
 *  - No raw payload and no email / phone / card data is ever stored.
 */

const TABLE = "sponsorships";

export type SponsorshipStatus = "pending" | "captured" | "refunded" | "failed";

const STATUS_RANK: Record<SponsorshipStatus, number> = {
  pending: 0,
  failed: 1,
  captured: 2,
  refunded: 3,
};

export interface SponsorshipPaymentInput {
  razorpayPaymentId: string;
  razorpayEventId: string | null;
  amountPaise: number;
  currency: string;
  /** What this delivery says happened. Refunds go through `markSponsorshipRefunded`. */
  status: "captured" | "failed";
  displayName: string | null;
  githubUsername: string | null;
  isAnonymous: boolean;
  showAmount: boolean;
  /** ISO timestamp of the payment. Required when `status` is "captured". */
  paidAt: string | null;
}

export type UpsertOutcome = "inserted" | "updated" | "unchanged";

/**
 * Records a captured or failed payment. At most two Supabase calls:
 * one read, then one write (and none on a plain replay).
 */
export async function upsertSponsorshipPayment(
  supabase: SupabaseClient,
  input: SponsorshipPaymentInput,
): Promise<UpsertOutcome> {
  if (input.status === "captured" && !input.paidAt) {
    // The table's CHECK would reject this anyway; fail clearly before the round trip.
    throw new Error("A captured sponsorship needs paidAt");
  }

  const { data: existing, error: readError } = await supabase
    .from(TABLE)
    .select("id, status")
    .eq("razorpay_payment_id", input.razorpayPaymentId)
    .maybeSingle();
  if (readError) throw new Error(`Failed to read ${TABLE}: ${readError.message}`);

  if (!existing) {
    // `approved` / `hidden` / `tier` are deliberately absent: defaults and
    // generated columns apply. onConflict covers two deliveries racing here.
    const { error } = await supabase.from(TABLE).upsert(
      {
        razorpay_payment_id: input.razorpayPaymentId,
        razorpay_event_id: input.razorpayEventId,
        amount_paise: input.amountPaise,
        currency: input.currency,
        status: input.status,
        display_name: input.displayName,
        github_username: input.githubUsername,
        is_anonymous: input.isAnonymous,
        show_amount: input.showAmount,
        source: "razorpay",
        paid_at: input.status === "captured" ? input.paidAt : null,
      },
      { onConflict: "razorpay_payment_id" },
    );
    if (error) throw new Error(`Failed to write ${TABLE}: ${error.message}`);
    return "inserted";
  }

  const currentRank = STATUS_RANK[existing.status as SponsorshipStatus] ?? 0;
  if (STATUS_RANK[input.status] <= currentRank) return "unchanged";

  const { error } = await supabase
    .from(TABLE)
    .update({
      status: input.status,
      razorpay_event_id: input.razorpayEventId,
      amount_paise: input.amountPaise,
      currency: input.currency,
      paid_at: input.status === "captured" ? input.paidAt : null,
    })
    .eq("id", existing.id);
  if (error) throw new Error(`Failed to update ${TABLE}: ${error.message}`);
  return "updated";
}

export type RefundOutcome = "refunded" | "unchanged" | "partial" | "not_found";

/**
 * Marks a payment refunded. Only a FULL refund changes the row: a partial
 * refund leaves the sponsor's remaining contribution counted, and the table
 * has no "partially refunded" state.
 *
 * `fullRefundHint` is what the payment entity says (true = full, false =
 * partial, null = unknown); when unknown, the refund amount is compared with
 * the stored `amount_paise`. Never creates a row — a refund for a payment we
 * never recorded is "not_found".
 */
export async function markSponsorshipRefunded(
  supabase: SupabaseClient,
  razorpayPaymentId: string,
  razorpayEventId: string | null,
  refundAmountPaise: number | null,
  fullRefundHint: boolean | null,
): Promise<RefundOutcome> {
  const { data: existing, error: readError } = await supabase
    .from(TABLE)
    .select("id, status, amount_paise")
    .eq("razorpay_payment_id", razorpayPaymentId)
    .maybeSingle();
  if (readError) throw new Error(`Failed to read ${TABLE}: ${readError.message}`);
  if (!existing) return "not_found";
  if (existing.status === "refunded") return "unchanged";

  const isFull =
    fullRefundHint ?? (refundAmountPaise !== null && refundAmountPaise >= (existing.amount_paise as number));
  if (!isFull) return "partial";

  const { error } = await supabase
    .from(TABLE)
    .update({ status: "refunded", razorpay_event_id: razorpayEventId })
    .eq("id", existing.id);
  if (error) throw new Error(`Failed to update ${TABLE}: ${error.message}`);
  return "refunded";
}
