import { Hono } from "hono";
import { getCookie } from "hono/cookie";
import { z } from "zod";
import type { Env, Variables } from "../types";
import { getEnv } from "../config/env";
import { getSupabase } from "../lib/supabase";
import {
  buildAuthorizeUrl,
  exchangeCodeForToken,
  fetchGitHubIdentity,
  GitHubOAuthError,
} from "../lib/github";
import { randomToken, sha256Hex, signCliOAuthState, verifyCliOAuthState } from "../lib/crypto";
import {
  CLI_OAUTH_STATE_COOKIE,
  setCliOAuthStateCookie,
  clearCliOAuthStateCookie,
} from "../lib/cookies";
import { upsertUserFromGitHub, toAuthUser } from "../db/users";
import { persistGithubTokens } from "../db/githubTokens";
import { createCliToken, revokeCliTokenByToken } from "../db/cliTokens";
import { createPendingCliLogin, consumePendingCliLogin } from "../lib/cliLoopback";
import { getIsMaintainer } from "../db/devtunnelStats";
import { checkRateLimit } from "../lib/rateLimit";
import { errorResponse } from "../lib/response";
import { logger } from "../lib/logger";

export const authCli = new Hono<{ Bindings: Env; Variables: Variables }>();

/**
 * Everything below implements the loopback pattern `gh`/`vercel`/`netlify`
 * use for browser-based OAuth from a CLI (RFC 8252):
 *
 *   1. `dev login` starts a local HTTP server on an ephemeral port and
 *      opens the system browser to `GET /auth/cli/start`, passing that
 *      port plus a PKCE-style `sha256(verifier)` challenge it generated
 *      itself.
 *   2. This backend runs the normal GitHub OAuth round trip against a
 *      *second* registered callback URL (`GITHUB_CLI_CALLBACK_URL`, see
 *      src/config/env.ts) instead of the web one, so it never touches
 *      `dt_session`/`dt_auth` or the web `/auth/callback` code path at
 *      all — the two flows are fully isolated.
 *   3. `GET /auth/cli/callback` finishes that round trip, then instead of
 *      setting a cookie, mints a short-lived one-time code
 *      (src/lib/cliLoopback.ts) and 302s the *browser* to
 *      `http://127.0.0.1:<port>/callback?code=...` — back into the CLI's
 *      own local server.
 *   4. The CLI reads that code off its local server and immediately
 *      exchanges it, server-to-server, at `POST /auth/cli/token`, proving
 *      it holds the original `verifier` (so a code intercepted in the
 *      loopback redirect alone isn't enough to redeem it) and receiving a
 *      real long-lived CLI bearer token in return.
 *
 * `POST /auth/cli/logout` is unrelated to the above — it just revokes a
 * bearer token a CLI already has, the same way `POST /auth/logout`
 * revokes a session cookie.
 */

const startQuerySchema = z.object({
  // Ephemeral loopback port devtunnel-cli is listening on for the
  // redirect back (src/routes/authCli.ts step 3 above). Restricted to the
  // unprivileged/ephemeral range so this can never be pointed at a
  // well-known port on the user's own machine.
  port: z.coerce.number().int().min(1024).max(65535),
  // sha256(verifier) hex, generated by the CLI (devtunnel-cli/src/lib/pkce.ts).
  challenge: z.string().regex(/^[0-9a-f]{64}$/i, "challenge must be a 64-char hex SHA-256 digest"),
});

/**
 * `GET /auth/cli/start` — opened in the system browser by `dev login`.
 * Mirrors `POST /auth/github` in src/routes/auth.ts, but as a GET (the
 * CLI opens this as a URL, it doesn't submit a form) and carrying the
 * loopback `port` + PKCE `challenge` instead of a post-login `next` path.
 */
authCli.get("/start", async (c) => {
  const env = getEnv(c.env);

  const withinLimit = await checkRateLimit(c, { bucket: "auth-cli-start", limit: 20, windowSeconds: 60 });
  if (!withinLimit) {
    return errorResponse(c, 429, "rate_limited", "Too many sign-in attempts. Try again shortly.");
  }

  const parsedQuery = startQuerySchema.safeParse({
    port: c.req.query("port"),
    challenge: c.req.query("challenge"),
  });
  if (!parsedQuery.success) {
    return errorResponse(
      c,
      400,
      "invalid_request",
      parsedQuery.error.issues[0]?.message ?? "Invalid or missing port/challenge",
    );
  }
  const { port, challenge } = parsedQuery.data;

  const state = randomToken(16);
  const signedCookie = await signCliOAuthState({ state, port, challenge }, env.SESSION_HMAC_SECRET);
  setCliOAuthStateCookie(c, env, signedCookie);

  return c.redirect(buildAuthorizeUrl(env, state, env.GITHUB_CLI_CALLBACK_URL), 302);
});

/** Minimal, dependency-free HTML shown in the browser tab if the CLI login flow fails. */
function cliErrorPage(reason: string): string {
  return `<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><title>DevTunnel CLI — sign-in failed</title></head>
<body style="font-family: -apple-system, sans-serif; max-width: 32rem; margin: 4rem auto; padding: 0 1rem; color: #1a1a1a;">
  <h1 style="font-size: 1.25rem;">Sign-in failed</h1>
  <p>DevTunnel couldn't complete GitHub sign-in for the CLI (${reason}).</p>
  <p>Go back to your terminal and run <code>dev login</code> again.</p>
  <p>You can close this tab.</p>
</body>
</html>`;
}

/**
 * `GET /auth/cli/callback` — GitHub-only endpoint, registered as
 * `GITHUB_CLI_CALLBACK_URL`. Never called directly by devtunnel-cli; the
 * browser lands here after the user approves (or denies) access on
 * GitHub, then gets redirected one more time into the CLI's own local
 * server.
 */
authCli.get("/callback", async (c) => {
  const env = getEnv(c.env);

  const withinLimit = await checkRateLimit(c, { bucket: "auth-cli-callback", limit: 20, windowSeconds: 60 });
  if (!withinLimit) {
    return c.html(cliErrorPage("rate_limited"), 429);
  }

  const code = c.req.query("code");
  const stateParam = c.req.query("state");
  const stateCookie = getCookie(c, CLI_OAUTH_STATE_COOKIE);
  clearCliOAuthStateCookie(c, env);

  if (!code || !stateParam || !stateCookie) {
    return c.html(cliErrorPage("access_denied"), 400);
  }

  const verified = await verifyCliOAuthState(stateCookie, env.SESSION_HMAC_SECRET);
  if (!verified || verified.state !== stateParam) {
    logger.warn("cli_oauth_state_mismatch", { requestId: c.get("requestId") });
    return c.html(cliErrorPage("invalid_state"), 400);
  }

  try {
    const tokens = await exchangeCodeForToken(env, code, env.GITHUB_CLI_CALLBACK_URL);
    const identity = await fetchGitHubIdentity(tokens.accessToken);

    const supabase = getSupabase(env);
    const userRow = await upsertUserFromGitHub(supabase, identity);

    // Best-effort, same posture as the web callback in src/routes/auth.ts —
    // not essential to signing in, never fails the request.
    try {
      await persistGithubTokens(supabase, env, userRow.id, tokens);
    } catch (err) {
      logger.error("cli_github_token_persist_failed", {
        userId: userRow.id,
        error: err instanceof Error ? err.message : String(err),
        requestId: c.get("requestId"),
      });
    }

    const loginCode = await createPendingCliLogin(c.env, {
      userId: userRow.id,
      challenge: verified.challenge,
    });

    const redirectTarget = new URL(`http://127.0.0.1:${verified.port}/callback`);
    redirectTarget.searchParams.set("code", loginCode);
    return c.redirect(redirectTarget.toString(), 302);
  } catch (err) {
    if (err instanceof GitHubOAuthError) {
      logger.warn("cli_github_oauth_failed", { reason: err.reason, requestId: c.get("requestId") });
      return c.html(cliErrorPage(err.reason), 400);
    }
    logger.error("cli_oauth_callback_failed", {
      error: err instanceof Error ? err.message : String(err),
      requestId: c.get("requestId"),
    });
    return c.html(cliErrorPage("server_error"), 500);
  }
});

const tokenBodySchema = z.object({
  code: z.string().min(1),
  verifier: z.string().min(43).max(256), // RFC 7636 PKCE verifier length bounds
  // Free-text label the CLI attaches to the token it's about to receive —
  // devtunnel-cli defaults this to the machine's hostname (see
  // devtunnel-cli/src/commands/login.ts) so `POST /auth/cli/logout` and
  // any future "manage my CLI sessions" screen have something readable to
  // show. Optional, never trusted for anything beyond display.
  label: z.string().trim().max(120).optional(),
});

/**
 * `POST /auth/cli/token` — called by devtunnel-cli's local loopback
 * server, not the browser, the instant it receives the redirect from
 * `GET /auth/cli/callback`. Exchanges the one-time `code` for a real,
 * long-lived CLI bearer token, after proving possession of the original
 * `verifier` (PKCE — see the module doc comment above).
 */
authCli.post("/token", async (c) => {
  const env = getEnv(c.env);

  const withinLimit = await checkRateLimit(c, { bucket: "auth-cli-token", limit: 10, windowSeconds: 60 });
  if (!withinLimit) {
    return errorResponse(c, 429, "rate_limited", "Too many requests. Try again shortly.");
  }

  let body: unknown;
  try {
    body = await c.req.json();
  } catch {
    return errorResponse(c, 400, "invalid_json", "Request body must be valid JSON");
  }

  const parsed = tokenBodySchema.safeParse(body);
  if (!parsed.success) {
    return errorResponse(c, 422, "validation_error", parsed.error.issues[0]?.message ?? "Invalid request");
  }
  const { code, verifier, label } = parsed.data;

  const pending = await consumePendingCliLogin(c.env, code);
  if (!pending) {
    return errorResponse(
      c,
      400,
      "invalid_grant",
      "This login code is invalid or has expired. Run `dev login` again.",
    );
  }

  const verifierHash = await sha256Hex(verifier);
  if (verifierHash !== pending.challenge) {
    logger.warn("cli_token_verifier_mismatch", { requestId: c.get("requestId") });
    return errorResponse(c, 400, "invalid_grant", "Login verification failed. Run `dev login` again.");
  }

  try {
    const supabase = getSupabase(env);
    const token = await createCliToken(supabase, pending.userId, label ?? null);

    const { data: userRow, error } = await supabase
      .from("users")
      .select()
      .eq("id", pending.userId)
      .maybeSingle();
    if (error || !userRow) {
      throw new Error(`Failed to load user after CLI token creation: ${error?.message ?? "no row"}`);
    }
    const isMaintainer = await getIsMaintainer(supabase, pending.userId);

    return c.json({ token, user: toAuthUser(userRow, isMaintainer) }, 200);
  } catch (err) {
    logger.error("cli_token_issue_failed", {
      error: err instanceof Error ? err.message : String(err),
      requestId: c.get("requestId"),
    });
    return errorResponse(c, 500, "internal_error", "Something went wrong");
  }
});

/**
 * `POST /auth/cli/logout` — called by `dev logout`. Reads the CLI's own
 * bearer token straight off the `Authorization` header (there is no
 * cookie in a CLI process to read it from), revokes it server-side, and
 * always returns success — mirrors `POST /auth/logout` in
 * src/routes/auth.ts: idempotent, and a stuck local credential file is
 * worse than a token row that simply expires on its own TTL.
 */
authCli.post("/logout", async (c) => {
  const env = getEnv(c.env);
  const authHeader = c.req.header("authorization") ?? c.req.header("Authorization");
  const token = authHeader?.toLowerCase().startsWith("bearer ") ? authHeader.slice(7).trim() : null;

  if (token) {
    try {
      const supabase = getSupabase(env);
      await revokeCliTokenByToken(supabase, token);
    } catch (err) {
      logger.error("cli_logout_revoke_failed", {
        error: err instanceof Error ? err.message : String(err),
        requestId: c.get("requestId"),
      });
    }
  }

  return c.json({ success: true }, 200);
});